const { chromium } = require('playwright');
const fs = require('node:fs');
(async()=>{
 const credentials=JSON.parse(fs.readFileSync(process.env.LIMU_TEST_LOGIN,'utf8'));
 const axe=fs.readFileSync(process.env.LIMU_AXE_PATH,'utf8');
 const browser=await chromium.launch({headless:true,executablePath:process.env.LIMU_CHROMIUM || '/usr/bin/chromium',args:['--no-sandbox']});
 const base=process.env.LIMU_TEST_URL||'http://127.0.0.1:8090';
 if(new URL(base).hostname!=='127.0.0.1')throw new Error('Browser test requires local disposable fixtures');
 const page=await browser.newPage({locale:'he-IL',viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const checks=[];
 async function check(condition,label){if(!condition)throw new Error(label);checks.push(label);console.log('PASS',label);}
 async function accessibility(label){await page.addScriptTag({content:axe});const r=await page.evaluate(()=>axe.run(document.body,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));if(r.violations.length)throw new Error(label+': '+JSON.stringify(r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))));checks.push('Accessibility '+label);console.log('PASS Accessibility',label);}
 async function dashboard(p=page){await p.getByRole('heading',{name:'סקירה כללית',exact:true}).waitFor();}
 async function login(p,account){await p.goto(base+'/crm/');if(await p.locator('#privacy-ack').isVisible())await p.locator('#privacy-ack').click();await p.getByLabel('שם משתמש או כתובת אימייל').fill(account.user);await p.getByLabel('סיסמה',{exact:true}).fill(account.password);await p.getByRole('button',{name:'כניסה למערכת'}).click();await dashboard(p);}
 try {
 await page.goto(base+'/crm/');await check(await page.getByRole('heading',{name:'ברוכים הבאים'}).isVisible(),'Dedicated CRM login loads');await accessibility('login');
 await check(await page.locator('#access-tools,#reading-guide,a[href*="m-d.co.il"]').count()===0&&await page.getByRole('link',{name:'הצהרת נגישות',exact:true}).count()===0,'Login omits removed accessibility controls, statement and footer credit');
 await check(!(await page.locator('body').textContent()).includes('מרחב ניהול מאובטח'),'Login omits the removed topbar wording');
 if(await page.locator('#privacy-ack').isVisible())await page.locator('#privacy-ack').click();
 await page.getByLabel('שם משתמש או כתובת אימייל').fill(credentials.user);await page.getByLabel('סיסמה',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'כניסה למערכת'}).click();
 await dashboard();await accessibility('dashboard');
 const allSummary=await page.evaluate(async()=>{const response=await fetch(window.LimuCRM.api+'summary',{headers:{'X-WP-Nonce':window.LimuCRM.nonce}});if(!response.ok)throw new Error('Summary fixture unavailable');return response.json();});
 await check(await page.locator('#filter-period').inputValue()==='all'&&!(await page.locator('#filter-month').isVisible())&&allSummary.historical>0&&(await page.locator('.metrics .value').first().textContent())===String(allSummary.leads)&&(await page.locator('.metrics .hint').first().textContent()).includes(`${allSummary.historical} פניות היסטוריות`),'Initial dashboard includes historical leads across all periods');
 await check(await page.locator('#access-tools,#reading-guide,a[href*="m-d.co.il"]').count()===0&&await page.getByRole('link',{name:'הצהרת נגישות',exact:true}).count()===0,'Authenticated portal omits removed controls, statement and credit');
 await check(!(await page.locator('body').textContent()).includes('מרחב ניהול מאובטח'),'Authenticated portal omits the removed topbar wording');
 await page.locator('#filter-period').selectOption('month');await page.locator('#filter-month').fill(new Date(new Date().getFullYear(),new Date().getMonth()-1,1).toLocaleDateString('sv-SE').slice(0,7));await page.getByRole('button',{name:'הצגת נתונים'}).click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 await check(Number(await page.locator('.metrics .value').first().textContent())<allSummary.leads,'Month filter narrows the displayed lead total');await page.locator('#reset-filters').click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 await check(await page.locator('#filter-period').inputValue()==='all'&&!(await page.locator('#filter-month').isVisible())&&(await page.locator('.metrics .value').first().textContent())===String(allSummary.leads),'Reset restores historical and live dashboard totals across all periods');
 const previousYear=String(new Date().getFullYear()-1);await page.locator('#filter-period').selectOption('year');await page.locator('#filter-year').fill(previousYear);await page.getByRole('button',{name:'הצגת נתונים'}).click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 const previousYearSummary=await page.evaluate(async year=>{const response=await fetch(window.LimuCRM.api+'summary?year='+year,{headers:{'X-WP-Nonce':window.LimuCRM.nonce}});if(!response.ok)throw new Error('Year summary fixture unavailable');return response.json();},previousYear);
 await check((await page.locator('.metrics .value').first().textContent())===String(previousYearSummary.leads)&&(await page.locator('.period-chip').textContent()).includes(previousYear)&&!(await page.locator('#filter-month').isVisible()),'Whole-year selection displays that year instead of adding a monthly constraint');
 const currentYear=String(new Date().getFullYear());await page.locator('#filter-year').fill(currentYear);await page.getByRole('button',{name:'הצגת נתונים'}).click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 const currentYearSummary=await page.evaluate(async year=>{const response=await fetch(window.LimuCRM.api+'summary?year='+year,{headers:{'X-WP-Nonce':window.LimuCRM.nonce}});if(!response.ok)throw new Error('Year summary fixture unavailable');return response.json();},currentYear);
 await check(currentYearSummary.leads>0&&(await page.locator('.metrics .value').first().textContent())===String(currentYearSummary.leads)&&(await page.locator('.period-chip').textContent()).includes(currentYear),'A populated year displays its historical and live leads');await page.locator('#reset-filters').click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 const rangeFrom=new Date(new Date().getFullYear(),new Date().getMonth()-1,1).toLocaleDateString('sv-SE'),rangeTo=new Date(new Date().getFullYear(),new Date().getMonth(),0).toLocaleDateString('sv-SE');
 await page.locator('#filter-period').selectOption('range');await page.locator('#filter-from').fill(rangeFrom);await page.locator('#filter-to').fill(rangeTo);await page.getByRole('button',{name:'הצגת נתונים'}).click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 const rangeSummary=await page.evaluate(async bounds=>{const response=await fetch(window.LimuCRM.api+'summary?'+new URLSearchParams(bounds),{headers:{'X-WP-Nonce':window.LimuCRM.nonce}});if(!response.ok)throw new Error('Date-range summary fixture unavailable');return response.json();},{date_from:rangeFrom,date_to:rangeTo});
 await check(rangeSummary.leads>0&&(await page.locator('.metrics .value').first().textContent())===String(rangeSummary.leads)&&(await page.locator('.period-chip').textContent()).includes(rangeFrom+' – '+rangeTo)&&!(await page.locator('#filter-month').isVisible())&&!(await page.locator('#filter-year').isVisible()),'Custom date range matches the actual scoped summary and replaces month and year filters');await page.locator('#reset-filters').click();await page.waitForFunction(()=>document.getElementById('screen').getAttribute('aria-busy')==='false');
 await page.screenshot({path:process.env.LIMU_SCREENSHOT_DIR+'/dashboard.png',fullPage:true});
 await page.locator('[data-view="deliveries"]').focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:'מרכז לידים',exact:true}).waitFor();await page.locator('tbody tr').first().waitFor();
 await check(await page.locator('[data-view="deliveries"]').getAttribute('aria-current')==='page'&&await page.evaluate(()=>document.activeElement===document.getElementById('main')),'Keyboard navigation selects the section and moves focus to its content');
 await check((await page.locator('tbody tr').count())>=4,'Lead list shows captured and historical rows');await accessibility('leads');
 const leadButton=page.locator('[data-detail]').first();await leadButton.focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await accessibility('lead dialog');await page.keyboard.press('Tab');await check(await page.evaluate(()=>!!document.activeElement.closest('dialog')),'Modal keeps keyboard focus inside the dialog');await page.keyboard.press('Escape');await check(!(await page.getByRole('dialog').isVisible())&&await leadButton.evaluate(element=>document.activeElement===element),'Escape closes the dialog and restores its trigger focus');
 await page.locator('[data-view="bills"]').click();await page.getByRole('heading',{name:'חיובים ותשלומים',exact:true}).waitFor();await accessibility('bills');
 await page.locator('[data-view="institutions"]').click();await page.getByRole('heading',{name:'מוסדות ותעריפים',exact:true}).waitFor();await accessibility('institutions');
 await page.locator('[data-rate]').first().click();await page.getByRole('dialog').waitFor();await check(await page.locator('#modal input[name="vat_percent"],#modal #vat').count()===0&&/18\s*%/.test(await page.locator('#modal').textContent()),'Institution tariff shows fixed 18 percent VAT without an editable VAT field');await accessibility('tariff dialog');await page.keyboard.press('Escape');
 await page.locator('[data-view="settings"]').click();await page.getByRole('heading',{name:'הגדרות והרשאות',exact:true}).waitFor();await accessibility('settings');
 await check(await page.getByRole('button',{name:'הוספת טופס'}).count()===0&&!/Elementor|חיבור טפסי/.test(await page.locator('#screen').textContent()),'Settings need no Elementor form mapping to receive native site leads');
 await check(await page.locator('#import,#import-progress').count()===0&&await page.getByRole('button',{name:'ייבוא היסטוריה',exact:true}).count()===0,'Settings omit the removed manual historical import interface');
 await page.setViewportSize({width:390,height:844});
 const checkboxLayout=await page.locator('#settings-form .check-label').evaluate(label=>{const input=label.querySelector('input'),text=label.querySelector('span'),labelBox=label.getBoundingClientRect(),inputBox=input.getBoundingClientRect(),textBox=text?.getBoundingClientRect();return {inputWidth:inputBox.width,inputHeight:inputBox.height,textFits:!!textBox&&textBox.left>=labelBox.left-1&&textBox.right<=labelBox.right+1,text:String(text?.textContent||'').trim(),noOverflow:document.documentElement.scrollWidth<=window.innerWidth};});
 await check(checkboxLayout.inputWidth>0&&checkboxLayout.inputWidth<=24&&checkboxLayout.inputHeight>0&&checkboxLayout.inputHeight<=24&&checkboxLayout.textFits&&checkboxLayout.text.length>0&&checkboxLayout.noOverflow&&await page.getByRole('checkbox',{name:/אישור חיובים אוטומטי/}).isVisible(),'Automatic approval remains a compact labeled checkbox with readable wrapping on mobile');
 await page.setViewportSize({width:720,height:500});await page.locator('[data-view="dashboard"]').focus();await page.keyboard.press('Enter');await dashboard();await check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)&&await page.getByRole('link',{name:'יציאה',exact:true}).isVisible(),'Portal reflows at a viewport equivalent to 200 percent zoom');await accessibility('zoom-equivalent viewport');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-view="deliveries"]').focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:'מרכז לידים',exact:true}).waitFor();await check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile lead table scrolls within its container without page overflow');await page.locator('[data-view="dashboard"]').click();await dashboard();await check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)&&await page.getByRole('link',{name:'יציאה',exact:true}).isVisible(),'Mobile dashboard has no horizontal overflow and keeps logout available');await accessibility('mobile');await page.screenshot({path:process.env.LIMU_SCREENSHOT_DIR+'/mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.locator('[data-view="reports"]').click();await page.getByRole('heading',{name:'דוחות וסיכומים',exact:true}).waitFor();await page.evaluate(()=>{window.print=()=>{};});await page.getByRole('button',{name:'הדפסה / שמירה כ־PDF'}).click();await page.waitForSelector('#print-snapshot',{state:'attached'});await check(await page.locator('#print-snapshot tbody tr').count()===2,'Print report includes all matching bills');await page.emulateMedia({media:'print'});await page.pdf({path:process.env.LIMU_SCREENSHOT_DIR+'/demo-billing.pdf',preferCSSPageSize:true,printBackground:true});await check(fs.statSync(process.env.LIMU_SCREENSHOT_DIR+'/demo-billing.pdf').size>1000,'Hebrew PDF report renders');await page.emulateMedia({media:'screen'});await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
 await check(errors.length===0,'No browser JavaScript errors');
 if(process.env.LIMU_MEMBER_LOGIN){
  const member=JSON.parse(fs.readFileSync(process.env.LIMU_MEMBER_LOGIN,'utf8'));const p=await browser.newPage();await login(p,member);
  await check(await p.locator('[data-view="institutions"]').count()===0,'Institution login hides manager navigation');
  const protectedResult=await p.evaluate(async()=>{const r=await fetch(window.LimuCRM.api+'settings',{method:'POST',headers:{'X-WP-Nonce':window.LimuCRM.nonce,'Content-Type':'application/json'},body:JSON.stringify({duplicate_mode:'rolling',start_date:''})});return r.status;});await check(protectedResult===403,'Real cookie-authenticated institution cannot change settings');await p.close();
 }
 console.log(`${checks.length} browser and accessibility checks passed.`);
 }finally{await browser.close();}
})().catch(error=>{console.error(error.message);process.exit(1)});
