import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, join } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const assets = join(root, 'limu-crm/assets');
const version = JSON.parse(await readFile(join(root, 'package.json'), 'utf8')).version;
const plugin = await readFile(join(root, 'limu-crm/limu-crm.php'), 'utf8');
if (!plugin.includes(`Version: ${version}\n`) || !plugin.includes(`define( 'LIMU_CRM_VERSION', '${version}' );`)) {
  throw new Error('Plugin and package versions must match before building.');
}

await build({
  entryPoints: ['crm.js', 'privacy.js', 'crm.css'].map(name => join(assets, name)),
  outdir: assets,
  entryNames: '[name].min',
  minify: true,
  logLevel: 'info',
});

const output = join(assets, 'build');
await mkdir(output, { recursive: true });
const manifest = {};
for (const name of ['crm.css', 'crm.js', 'privacy.js']) {
  const [base, extension] = name.split('.');
  const bytes = await readFile(join(assets, `${base}.min.${extension}`));
  const fingerprint = createHash('sha256').update(bytes).digest('hex').slice(0, 12);
  const file = `${base}.${fingerprint}.min.${extension}`;
  await writeFile(join(output, file), bytes);
  manifest[name] = `build/${file}`;
}

const generated = `<?php
/**
 * Generated asset paths. Rebuild with npm run build after changing sources.
 *
 * @package LimuCRM
 */

namespace LimuCRM;

if ( ! defined( 'ABSPATH' ) ) {
\texit;
}

const ASSETS = array(
${Object.entries(manifest).map(([name, file]) => `\t'${name}'${' '.repeat(11-name.length)}=> '${file}',`).join('\n')}
);
`;
await writeFile(join(root, 'limu-crm/includes/assets.php'), generated);

// Only remove obsolete files generated by this script. Stable aliases support old open pages.
const current = new Set(Object.values(manifest).map(file => file.slice('build/'.length)));
for (const file of await readdir(output)) {
  if (/^(?:crm|privacy)\.[a-f0-9]{12}\.min\.(?:js|css)$/.test(file) && !current.has(file)) {
    await unlink(resolve(output, file));
  }
}
